### ISSUE TITLE
Only plugin manual available

### ISSUE THREAD

**Issue by Rasbats** [leamas/manual_pi#2]
Was this intended?

**Comment by Rasbats** [comment]
Probably. Closing.

**Comment by leamas** [comment]
no, it was not. Reopening

**Comment by leamas** [comment]
Ah... The catalog has two entries. One could assume that tagged entry was the correct, but the best version is actually 0.0.1+197.405ad5b.

My bad. Need to update the catalog

**Comment by leamas** [comment]
BTW: If you are interested, this also demonstrates how to make a test build available for others without having to make a PR to opencpn/plugins. The process is documented [here](https://github.com/leamas/plugins/blob/master/TESTING.md#publish-a-private-catalog) and actually quite simple.

**Comment by Rasbats** [comment]
Great work done by Pavel and yourself. I hesitated adding a comment to avoid controversy. But ... if the beginners manual was less verbose I would be interested in creating a multi-language version, as done for InlandEcdis using the CoastSystems work.

**Comment by leamas** [comment]
I take your comments as if all now is ok, thus closing.

>  if the beginners manual was less verbose I would be interested in creating a multi-language version

I think we should think twice before doing that. Even if we somehow managed to make some translations, how should they be maintained? As of now we obviously fail to maintain even a single, English version.
