### ISSUE TITLE
some little hyperlinks  problems in some html files inside /doc/ folder and some of its subfolders 

### ISSUE THREAD

**Issue by filochard** [leamas/manual_pi#5]
Hi Alec
I know that's a work in progress and I am not sure that what I propose will be useful 
Nevertheless
I found some links problem in /doc/user-manual/opencpn/manual_basic.html opened , as it is now, inside Firefox

here is a little patch that I had to rename manual-basic-html.patch.txt since .diff or .patch couldn't be uploaded (if you remove the .txt extension you may use it : 
[manual-basic-html.diff.txt](https://github.com/user-attachments/files/17350765/manual-basic-html.diff.txt)

Besides this some links lead to nowhere yet : 
/opencpn/supplementary_hardware.html      ..............................................................................................line 589    in manual_basic.html
   /opencpn/supplementary_software.html    .............................................................................................. line 592   in manual_basic.html
Basic User Manual Table of Contents  ............aka /opencpn/toc_manual_basic.html  ..............line 601    in manual_basic.html
Advanced User Manual Table of Contents ....aka /opencpn/toc_manual_advanced.html....line 604   in manual_basic.html

**Comment by filochard** [comment]
Hi Alec
As you may know I continue to build rpms for opencpn and its plugins
I am testing manual_pi inside flatpak and inside a rpm installation
I have found some hyperlinks problems in both of them 

I have manually modified some html files in a doc folder extracted for the manual_pi-0.0.3.tar.gz and tested then this modified links they are OK
/doc/plugin-dev-manual/ocpn-dev-manual/0.1/index.html
/doc/plugin-dev-manual/ocpn-dev-manual/0.1/intro-AboutThisManual.html
/doc/user-manual/opencpn/manual_basic.html
/doc/index.html

Building rpm allows me to apply some patches to correct the source so that those hyperlinks work correctly
here is the list (I have had to change the .patch extension to .txt to upload them into github
[ocpn-dev-manual-index-html.txt](https://github.com/user-attachments/files/17534312/ocpn-dev-manual-index-html.txt)
[ocpn-dev-manual-intro-AboutThisManual-html.txt](https://github.com/user-attachments/files/17534326/ocpn-dev-manual-intro-AboutThisManual-html.txt)
[ocpn-manual_basic-html.txt](https://github.com/user-attachments/files/17534327/ocpn-manual_basic-html.txt)

I got some problem with this following patch (hunk failed with no understandable reason)
[ocpn-doc-main-index-html.txt](https://github.com/user-attachments/files/17534334/ocpn-doc-main-index-html.txt)
but if I manually modify this file in a doc folder extracted for the manual_pi-0.0.3.tar.gz it's OK

**Comment by filochard** [comment]
PS here is my spec file (it might work for Fedora)
[opencpn-manuals-plugin.spec.txt](https://github.com/user-attachments/files/17534365/opencpn-manuals-plugin.spec.txt)
and two extra patches
[opencpn-libs-1a6c1a7-json.patch.txt](https://github.com/user-attachments/files/17534367/opencpn-libs-1a6c1a7-json.patch.txt)
[opencpn-libs-1a6c1a7-tinyxml.patch.txt](https://github.com/user-attachments/files/17534371/opencpn-libs-1a6c1a7-tinyxml.patch.txt)

**Comment by leamas** [comment]
> I have found some hyperlinks problems in both of them

Sorry for late reply.

However, this is not the place to report errors on the manual as such. This repo is only about publishing the user manual such as it is.

To make it more interesting there is no natural place to report errors in the manual since it's not under version control. What you could do is to open a discussion in https://github.com/OpenCPN/OpenCPN. However, the best alternative is a thread in zulip which lives  at https://opencpn.zulipchat.com/. In any case you should address Rick Gleason a k a rgleason here on github.

**Comment by leamas** [comment]
Closing this for reasons described above

**Comment by filochard** [comment]
@rgleason ^
